hooroo/roo-ui

packages/components/src/BlockLink/BlockLink.story.js, packages/components/src/BlockLink/__snapshots__/BlockLink.test.js.snap, packages/components/src/Box/Box.story.js, packages/components/src/Button/__snapshots__/Button.test.js.snap, packages/components/src/Card/Card.story.js, packages/components/src/Card/__snapshots__/Card.test.js.snap, packages/components/src/Container/Container.story.js, packages/components/src/Flex/Flex.story.js, packages/components/src/Heading/__snapshots__/Heading.test.js.snap, packages/components/src/Input/Input.js, packages/components/src/Input/__snapshots__/Input.test.js.snap, packages/components/src/Label/Label.js, packages/components/src/Label/__snapshots__/Label.test.js.snap, packages/components/src/Link/__snapshots__/Link.test.js.snap, packages/components/src/OutlineButton/__snapshots__/OutlineButton.test.js.snap, packages/components/src/Text/Text.js, packages/components/src/Text/__snapshots__/Text.test.js.snap, packages/components/src/Truncate/__snapshots__/Truncate.test.js.snap, packages/themes/src/qantas.js
Removed greys we're not using, now we only have:
=> refactor: reduce number of greys

packages/icons/src/rating/circle_half.svg
Circle half icon not centred in bounding box after sketch export. See gif
Recreating and exporting via Illustrator solves the alignment problem.
=> fix: refine circle half icon

packages/components/src/Input/Input.js, packages/components/src/Input/Input.story.js, packages/components/src/Input/__snapshots__/Input.test.js.snap, packages/components/src/PasswordInput/__snapshots__/PasswordInput.test.js.snap
**What**
Add's a style for read only inputs. Loses background & border colours and is left aligned to label.
See the email input in the image below.
=> feat: add read only input style

packages/components/src/Input/Input.js, packages/components/src/Input/Input.story.js, packages/components/src/Input/__snapshots__/Input.test.js.snap, packages/components/src/PasswordInput/__snapshots__/PasswordInput.test.js.snap, packages/components/src/Select/__snapshots__/Select.test.js.snap, packages/components/src/Textarea/__snapshots__/Textarea.test.js.snap
TODO: Update snapshots for `Textarea` and `Select`(?) once respective branches are merged in.
=> chore: add underlined input variant

packages/components/src/Autocomplete/Autocomplete.js, packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.js.snap, packages/components/src/MaskedInput/MaskedInput.js, packages/components/src/MaskedInput/MaskedInput.story.js, packages/components/src/MaskedInput/__snapshots__/MaskedInput.test.js.snap
- reverts masked input workaround
- fixes props passed into `MaskedInput` as attributes
- changes `MaskedInput` placeholderChar to `\u2000`
- add z-index to `Autocomplete` menu item to display over `Radio`
=> fix: revert masked input workaround

packages/components/src/Dropdown/Dropdown.js
* Reduce min-width.
* Remove underline when `Dropdown.item` is a link.
=> Dropdown styling tweaks

packages/components/src/Autocomplete/Autocomplete.js, packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.js.snap
- Limits `Autocomplete` menu to five items.
=> refactor: add maxHeight to Autocomplete menu

packages/components/src/LoadingIndicator/LoadingIndicator.js, packages/components/src/LoadingIndicator/__snapshots__/LoadingIndicator.test.js.snap
- Use the theme default transition for fade in; more consistent, and the current fade in feels a bit slow IMO
- Add space between bouncers (consistent with Qantas usage, also looks a little weird currently as the circles are touching at full size)
=> refactor: loading indicator tweaks

packages/components/src/MaskedInput/MaskedInput.js, packages/components/src/MaskedInput/__snapshots__/MaskedInput.test.js.snap
Ran into an issue where I wanted to extend `MaskedInput` and add a style based on a prop.
`MaskedInput` was not a `clean-tag` element so it added my prop to the html, which caused React to throw this warning `React does not recognize the "calendarOpen" prop on a DOM element.`
This fix returns our own `Input` component in the render method. This means the input is a `clean-tag` element and we can use the `blacklist` prop. I also forwarded on the `Input` defaultProps, so that  I can extend the `blacklist` and remove the React warning.
@angusfretwell mentioned this could potentially break what you are working on @jonathanly. So would be awesome if you could test this change out in your `Formik` branch.
=> Forward on default props and use Input which is a clean tag element

packages/components/src/Dropdown/Dropdown.js, packages/components/src/NakedButton/NakedButton.js, packages/components/src/NakedButton/__snapshots__/NakedButton.test.js.snap
This allows `NakedButton` and `Dropdown` to be correctly vertically centred with flex.
=> refactor: vertically align inline blocks

packages/components/src/Calendar/components/CalendarNav/CalendarNav.js
We missed this small change before. Added padding to nav so it always lines up with calendar month.
Might want to compare it to master once the other build goes through. Only touched one file.
=> fix: add padding to calendar nav

packages/components/src/Calendar/components/CalendarDays/CalendarDays.js, packages/components/src/Calendar/components/CalendarDays/__snapshots__/CalendarDays.test.js.snap
**What**
Fixes issue in IE where calendar days had no width. 
**Fix**
Using `width` instead of `flex-basis` made it display perfectly.
=> fix: in calendar use width instead of flex-basis 

packages/components/src/Box/Box.js, packages/components/src/Box/README.md, packages/components/src/Popover/Popover.js, packages/components/src/Popover/Popover.story.js, packages/components/src/Popover/README.md, packages/components/src/Popover/__snapshots__/Popover.test.js.snap
**What**
Update two issues we had when using `Popover`.
1. Add a grey outline to `Popover`. We didn't have enough contrast and its what Qantas uses.
2. Add ability to change `z-index`.
=> refactor: update popover styles

package.json, packages/components/package.json, packages/components/src/Calendar/components/CalendarDays/__snapshots__/CalendarDays.test.js.snap, packages/components/src/Calendar/components/CalendarNav/__snapshots__/CalendarNav.test.js.snap, packages/components/src/Dropdown/Dropdown.js, packages/components/src/Dropdown/__snapshots__/Dropdown.test.js.snap, packages/components/src/NakedButton/NakedButton.js, packages/components/src/NakedButton/README.md, packages/components/src/NakedButton/__snapshots__/NakedButton.test.js.snap, yarn.lock
So, this was a mistake. Added `verticalAlign` prop instead of setting it to `middle` always.
=> refactor: dont add vertical align to naked button by default

packages/components/src/StarRating/README.md, packages/components/src/StarRating/StarRating.js
- Allow number or string for rating and icon size
- Restrict rating type to `'AAA'` or `'SELF_RATED'`
=> refactor: update star rating props

packages/components/src/Calendar/Calendar.js, packages/components/src/Calendar/Calendar.story.js, packages/components/src/Calendar/Calendar.test.js, packages/components/src/Calendar/README.md, packages/components/src/Calendar/__snapshots__/Calendar.test.js.snap, packages/components/src/Calendar/components/CalendarDays/CalendarDays.js
**What**
In our use case we need to differentiate disabled days which are outside of the calendar range and disabled days inside the range.
This change allows us to receive the click event from a disabled day inside the calendar range.
**Fix**
- Add `interactiveDisabledDates` prop.
- Darken disabled date when clicked.
**Future**
This solution might not apply to other teams. Lets discuss it next working group with some possible solutions.  See [here](https://github.com/hooroo/roo-ui/issues/128).
=> feat: add props to allow disabled calendar dates to be clicked

packages/components/src/Flex/Flex.js, packages/components/src/Flex/README.md
`flexFlow` is shorthand for `flexDirection` and `flexWrap` 
It's a nice to have but it is nice!
https://developer.mozilla.org/en-US/docs/Web/CSS/flex-flow
=> feat: add flexFlow shorthand css Property

packages/assets/story.js, packages/components/src/Alert/Alert.js, packages/components/src/Alert/__snapshots__/Alert.test.js.snap, packages/components/src/Autocomplete/Autocomplete.js, packages/components/src/BlockLink/BlockLink.story.js, packages/components/src/Box/Box.story.js, packages/components/src/Calendar/components/CalendarDays/CalendarDays.js, packages/components/src/Calendar/components/CalendarNav/CalendarNav.js, packages/components/src/Calendar/components/CalendarWeekdays/CalendarWeekdays.js, packages/components/src/Card/Card.story.js, packages/components/src/Checkbox/Checkbox.js, packages/components/src/Container/Container.story.js, packages/components/src/Dropdown/Dropdown.js, packages/components/src/ExternalLink/ExternalLink.js, packages/components/src/Flex/Flex.story.js, packages/components/src/Icon/Icon.story.js, packages/components/src/Input/Input.js, packages/components/src/LoadingIndicator/LoadingIndicator.js, packages/components/src/LoadingIndicator/README.md, packages/components/src/LoadingIndicator/__snapshots__/LoadingIndicator.test.js.snap, packages/components/src/PasswordInput/PasswordInput.js, packages/components/src/Popover/Popover.js, packages/components/src/Radio/Radio.js, packages/themes/src/qantas.js
With the need for a new grey comes the need to move from an array to an object.
For the grey colors in theme/qantas.js:
Key -> from *grey* to **greys**
Value -> from an *array* to an **object**.
Replace: 
`colors.grey.0` with `colors.greys.charcoal`
`colors.grey.1` with `colors.greys.steel`
`colors.grey.2` with `colors.greys.alto`
`colors.grey.3` with `colors.greys.porcelain`
NEW!
`colors.greys.dusty`  (`#999999`)
=> feat(greys): converts greys array to an object and introduces a new grey

packages/components/src/Calendar/Calendar.story.js, packages/components/src/Calendar/components/CalendarDays/CalendarDays.js, packages/components/src/Calendar/components/CalendarDays/CalendarDays.test.js, packages/components/src/Calendar/components/CalendarDays/__snapshots__/CalendarDays.test.js.snap
**What**
- Storybook was broken due to a missed grey rename.
- Calendar days had no height in Firefox.
- When multiple dates are selected the calendar had double borders.
**Fix**
- Update grey color
- Fix Firefox browser bug
- Use the parent element to control the border color
- Update to remove double borders
=> fix: calendar tweaks

packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.js.snap, packages/components/src/Checkbox/__snapshots__/Checkbox.test.js.snap, packages/components/src/Popover/__snapshots__/Popover.test.js.snap, packages/components/src/Radio/__snapshots__/Radio.test.js.snap, packages/test-utils/src/mountWithTheme.js, packages/test-utils/src/shallowWithTheme.js
**What**
With our current setup, the theme is only passed to the top level component. When you `mount` a component or `dive` the child component theme values are undefined.
So far this has not caused any issues. We ran into an issue where a `styled-system` function threw an error because the theme value undefined.
**Fix**
Found the fix on this [thread](https://github.com/styled-components/jest-styled-components/issues/106) and they have update their docs recently.
Solution is to pass this down when mounting `childContextTypes: ThemeProvider.childContextTypes`
=> fix: pass theme to child components; update snapshots

packages/components/src/StarRating/StarRating.js, packages/components/src/StarRating/__snapshots__/StarRating.test.js.snap, packages/themes/src/ThemeProvider.js, packages/themes/src/qantas.js
closes #138 
Add generic colour names for the rest of the colours. 
Not all of them are using the colour naming tool. For instance the colour naming tool would of given us the name `blackSqueeze` for `lightBlue`.
=> refactor: add generic colour names

.eslintrc, packages/components/package.json, packages/components/src/Modal/Modal.js, packages/components/src/Modal/Model.story.js, packages/components/src/Modal/Model.test.js, packages/components/src/Modal/README.md, packages/components/src/Modal/__snapshots__/Model.test.js.snap, packages/components/src/Modal/components/ModalBody/ModalBody.js, packages/components/src/Modal/components/ModalBody/ModalBody.test.js, packages/components/src/Modal/components/ModalBody/__snapshots__/ModalBody.test.js.snap, packages/components/src/Modal/components/ModalBody/index.js, packages/components/src/Modal/components/ModalFooter/ModalFooter.js, packages/components/src/Modal/components/ModalFooter/ModalFooter.test.js, packages/components/src/Modal/components/ModalFooter/__snapshots__/ModalFooter.test.js.snap, packages/components/src/Modal/components/ModalFooter/index.js, packages/components/src/Modal/components/ModalHeader/ModalHeader.js, packages/components/src/Modal/components/ModalHeader/ModalHeader.test.js, packages/components/src/Modal/components/ModalHeader/__snapshots__/ModalHeader.test.js.snap, packages/components/src/Modal/components/ModalHeader/index.js, packages/components/src/Modal/index.js, packages/components/src/index.js, packages/themes/src/qantas.js, yarn.lock
New `Modal` Component:
This component support same props as [react-modal](https://github.com/reactjs/react-modal/blob/v3.5.1/docs/README.md#general-usage-usage).
| Name        | Description                                                             | Type     | Default   | Required? |
|-------------|-------------------------------------------------------------------------|----------|-----------|-----------|
| `icon`      | render an icon                                                          | `shape`  | -         | -         |
| `variant`   | `alertStyle` from theme. One of `default`, `info`, `success` or `error` | `string` | 'default' | -         |
This component support same props as [Box](https://github.com/hooroo/roo-ui/tree/master/packages/components/src/Box/README.md).
This …
=> feat: Add Modal component

packages/components/src/DatePicker/components/CalendarDay/CalendarDay.js
=> Remove the border from the focus state of the DateRangePicker day

packages/components/src/DatePicker/components/CalendarDay/CalendarDay.js
With the recent calendar work we have lost the focus style.
This adds the same focus style to the selected calendar day.
@KamalMicheal Check that this ok with your date range calendar. Right now you are missing a focus style as well.
=> fix: add focus style to calendar day

packages/components/src/DatePicker/DateRangePicker.README.md, packages/components/src/DatePicker/DateRangePicker.js, packages/components/src/DatePicker/DateRangePicker.story.js, packages/components/src/DatePicker/DateRangePicker.test.js, packages/components/src/DatePicker/components/CalendarDay/CalendarDay.js, packages/components/src/DatePicker/components/CalendarDay/__snapshots__/CalendarDay.test.js.snap, packages/components/src/DatePicker/components/CalendarDays/CalendarDays.test.js, packages/components/src/DatePicker/components/CalendarMonth/CalendarMonth.js, packages/components/src/DatePicker/components/CalendarMonth/__snapshots__/CalendarMonth.test.js.snap
The date range picker had a problem where if you have preselected dates, it would select them correctly but not update which month to show. You would always see the current month until nav controls were used to find the currently selected dates.
I've updated the props to better describe what they are doing and unified the seperate start and end callbacks into a single callback, to avoid a setState bug we were encountering.
I've also remove input that were not being used and updated the styling in places
=> fix: DateRangePicker offset bug and props refactor

packages/components/src/DatePicker/DateRangePicker.js
The `onMouseEnterOfDay` function was supposed to be throttled, but because of the way throttle was called inside the function, it was just creating a new throttle on every execution.
The throttle is now wrapping the function correctly.
=> Fix throttle function call

packages/components/src/DatePicker/DateRangePicker.js, packages/components/src/DatePicker/DateRangePicker.test.js
There were some tests that were relying on the current date, now that it's October 1st, they are breaking. This PR allows you to:
- set a fixed focus date on the calendar so that deterministic tests can be written - fixes those tests that broke in a way that they won't break in 30 days time
=> fix: datepicker tests that rely on current date

packages/components/src/Popover/lib/svg-classlist-polyfill.js
When a server side rendered app tries to start and doesn't have access to window it blows up on this SVG polyfill code.
This is a quickfix to make sure it has window before it executes. The long term fix is to look at removing the PopOver component from roo-ui https://github.com/hooroo/roo-ui/issues/178
=> Checks for window before runnig svg-polyfill to prevent SSR blowing up

packages/components/src/Button/__snapshots__/Button.test.js.snap, packages/components/src/NakedButton/NakedButton.js, packages/components/src/NakedButton/__snapshots__/NakedButton.test.js.snap, packages/components/src/OutlineButton/__snapshots__/OutlineButton.test.js.snap, packages/themes/src/qantas.js
- Update `<NakedButton />` focus style to match Link
- Set a stronger focus shadow For `<Button />`
`NakedButton`
`NakedButton:focus`
`Button`
`Button:focus`
=> Update focus styles

package.json, packages/components/package.json, packages/components/src/Hide/Hide.js, packages/components/src/Hide/Hide.story.js, packages/components/src/Hide/Hide.test.js, packages/components/src/Hide/__snapshots__/Hide.test.js.snap, yarn.lock
`<Hide />`s media query rules were overlapping by 1px. For example, consider `<Hide sm>1</Hide>` `<Hide xs />2</Hide>` with breakpoints `['768px', '1100px', '1280px']` and a viewport `768px` wide. In this scenario both 1 and 2 would be hidden.
`max-width` media rules now shave `1px` off the breakpoint
I've used a function from `v2` of polished so I've upgraded the peer dependancy version to match
=> fix: overlapping breakpoints in <Hide />

.eslintignore, packages/components/src/BlockLink/__snapshots__/BlockLink.test.js.snap, packages/components/src/ExternalLink/__snapshots__/ExternalLink.test.js.snap, packages/components/src/Link/Link.js, packages/components/src/Link/Link.story.js, packages/components/src/Link/__snapshots__/Link.test.js.snap
**Breaking change**: Renames Link `inline` prop to `underline`
Closes https://github.com/hooroo/roo-ui/issues/193
=> fix: rename link inline prop

.eslintignore, packages/components/src/Button/Button.js, packages/components/src/Button/__snapshots__/Button.test.js.snap, packages/components/src/OutlineButton/__snapshots__/OutlineButton.test.js.snap, packages/themes/src/qantas.js
Our buttons (Button and NakedButton) in a disabled state should be inline with other Qantas apps (we've used book.qantas.com and qantas assure as our example).
Should look like this:
**Before**:
**After**:
=> refactor: Add new disabled style for Button and OutlineButton

packages/components/src/Button/Button.js, packages/components/src/Button/__snapshots__/Button.test.js.snap, packages/components/src/OutlineButton/OutlineButton.js, packages/components/src/OutlineButton/__snapshots__/OutlineButton.test.js.snap
This is to correct invalid styling on OutlineButton introduced in PR #203 ,
and to lighten both Button and OutlineButton in "disabled" state as per qantas.com and qantasassure.com disabled buttons.
As per design: https://app.zeplin.io/project/5b346e17992a080a5c0ac387/screen/5bbe9407ba5e2a09d44757f5
Disabled Button:
Disabled OutlineButton:
=> Lighten Button disabled state and correct OutlineButton disabled state

packages/components/src/Label/Label.js, packages/components/src/Label/__snapshots__/Label.test.js.snap
By switching from fixed styles using `themeGet` to default props, we allow apps to change the margins without extending the components.
=> Allow label margins to be changed without extending

packages/components/src/Button/Button.js, packages/components/src/OutlineButton/__snapshots__/OutlineButton.test.js.snap
This PR makes the Button more resilient to extension. Previously we had seen to issues:
1. The only way to create a variant that with different hover styles was to add specificity in a non-standard way `'&&:hover:not(:disabled)'`
2. If a background color was non explicitly set, the darken function from polished would receive null and throw a cryptic error that was hard to debug.
=> update Button to be more resilliant to extension

packages/components/src/DatePicker/DatePicker.js, packages/components/src/DatePicker/DatePicker.test.js, packages/components/src/DatePicker/DateRangePicker.js, packages/components/src/DatePicker/DateRangePicker.test.js, packages/components/src/DatePicker/components/CalendarDays/CalendarDays.test.js, packages/components/src/DatePicker/components/CalendarMonth/CalendarMonth.test.js, packages/components/src/DatePicker/lib/isDateInRange.js
This PR changes the way that we import `date-fns` so that we are not bundling the whole library in the bundle
=> reduce date-fns bundle size

packages/components/src/Input/Input.js, packages/components/src/Input/__snapshots__/Input.test.js.snap, packages/components/src/MaskedInput/__snapshots__/MaskedInput.test.js.snap, packages/components/src/PasswordInput/PasswordInput.js, packages/components/src/PasswordInput/__snapshots__/PasswordInput.test.js.snap, packages/components/src/Select/__snapshots__/Select.test.js.snap, packages/components/src/Textarea/__snapshots__/Textarea.test.js.snap, packages/themes/src/qantas.js
We have a few designs in our app where we need to set an input to readonly, but we still want it to look like an input (just greyed out). The only way to do this right now is to extend the component and then overwrite the css (which bloats the css that styled components outputs).
The last version of `styled-system` has consolidated many utilities into the `variant` function which is used here to make the readonly styled extensible.
=> Allow Input to accept readonly variations

packages/components/src/Box/Box.js, packages/components/src/Label/Label.js, packages/components/src/Link/Link.js, packages/components/src/Text/Text.js, packages/components/src/styledOmitProps/styledOmitProps.js, packages/components/src/styledOmitProps/styledOmitProps.test.js
Use `styledOmitProps` for commonly used base components: Box, Label, Link & Text.
I stop short of using it in `Heading` as I notice the omit functionality doesn't work when using styled-components `as` prop.
But adding in on the above components brought the number of DOM nodes with leaked attributes down from ~900 to ~50.
For reference, this is how I tested for leaked props
```js
document.querySelectorAll('[m]:not(svg):not(img), [margin]:not(svg):not(img), [mt]:not(svg):not(img), [margin-top]:not(svg):not(img), [mr]:not(svg):not(img), [margin-right]:not(svg):not(img), [mb]:not(svg):not(img), [margin-bottom]:not(svg):not(img), [ml]:not(svg):not(img), [margin-left]:not(svg):not(img), [mx]:not(svg):not(img), [my]:not(svg):not(img), [p]:not(svg):not(img), [padding]:not(svg):not(img), …
```
=> feat: Use styledOmitProps for Box, Label, Link & Text

packages/components/src/Checkbox/Checkbox.js
The `font-size` of the checkbox should be fixed, if it is not, it will inherit the containers `font-size` which will potentially change the vertical alignment of the tick svg, which means the checkbox will look incorrect.
=> fix: add fixed fontsize to checkbox

packages/components/src/Button/Button.js, packages/components/src/OutlineButton/__snapshots__/OutlineButton.test.js.snap
Even though we have the `block` prop, we have run into trouble when using `as` in conjunction with it, so it would be good if we could set the `display` prop using styled systems helper.
=> allow display to be overidden in Button component

packages/components/src/Box/Box.js, packages/components/src/Box/README.md, packages/components/src/Popover/__snapshots__/Popover.test.js.snap
We have `position` on `Box` but are missing positional attributes.
This PR Adds `top`, `right`, `bottom`, `left` to `Box`
=> feat: add position attributes to Box

packages/themes/src/qantas.js
Makes the label line height consistent with text line height. Label currently defaults to the base-line height of 1.35 which is subtly different to that of Text which is 1.5. This makes aligning these two elements vertically along a horizontal axis harder than it could be.
Happy to hear reasons why this is a bad idea but hoping it won't impact any other app.
=> make label line-height consistent with text

README.md, babel.config.js, packages/components/src/Alert/__snapshots__/Alert.test.js.snap, packages/components/src/Checkbox/__snapshots__/Checkbox.test.js.snap, packages/components/src/DatePicker/components/CalendarNav/__snapshots__/CalendarNav.test.js.snap, packages/components/src/Icon/Icon.js, packages/components/src/Icon/Icon.story.js, packages/components/src/Icon/Icon.test.js, packages/components/src/Icon/__snapshots__/Icon.test.js.snap, packages/components/src/PasswordInput/__snapshots__/PasswordInput.test.js.snap, packages/icons/package.json, packages/icons/parseIcons.js, packages/icons/src/index.js, packages/themes/src/defaultIcons.js, packages/themes/src/qantas.js, yarn.lock
Export svg icon paths as es-module, allowing them to be treeshaked by consuming apps.
If you need more icons than what's included in `packages/themes/src/defaultIcons.js`. Add them to your apps theme:
```js
// my-app/icons.js
export { arrowUpward, arrowForward } from '@roo-ui/icons';
// my-app/theme.js
import * as icons from './icons';
export default {
...qantas,
icons: {
...qantas.icons,
...icons,
},
};
```
=> Tree shakable icons

packages/components/src/Input/Input.js, packages/components/src/PasswordInput/__snapshots__/PasswordInput.test.js.snap
Update disabled input styles to match qantas style guide 
*Ignore the difference in width*
=> Update disabled input styles

babel.config.js, package.json, packages/assets/package.json, packages/components/package.json, packages/icons/generateEcmaScriptModule.js, packages/icons/package.json, packages/icons/parseIcons.js, packages/logos/package.json, packages/test-utils/package.json, packages/themes/package.json, yarn.lock
This PR creates both esm & cjs builds.
**Why?**
Jest configured by Create React App does not compile `node_modules`. And CRA disables the relevant jest configuration option.
=> Create both esm & cjs builds

packages/components/src/Button/Button.js
We often want to render block buttons for mobile and dynamically sized buttons for larger viewports.
Adding width allows us to do this 
```jsx
<Button width={['100%', 'auto']} />
```
=> Add `width` styled function to Button

packages/components/src/ExternalLink/ExternalLink.js
I would question whether we need the ExternalLink component at all, but we had a card up to make color over-writable, so here it is.
=> ensure color is overridable in ExternalLink

src/components/Hide/Hide.js
There was a deprecation warning coming out of the new version of polished. I wish they had of just kept the API the same, a Boolean second argument with no context to the function name always feels like a code smell. 
Oh well 🤷🏻‍♂️ this will silence the warnings.
=> fix: refactor deprecated function

package.json
With `side-effects: false` in `package.json`, `roo-ui/fonts/ciutadella.css` is omitted from production builds in consuming apps. 
This PR marks all css files as having side effects.
https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
=> fix: mark css files as having side effects

src/components/Box/Box.js, src/components/Popover/__snapshots__/Popover.test.js.snap
Closes https://github.com/hooroo/roo-ui/issues/259
See https://github.com/hooroo/self-service/blob/master/src/components/Layout/Card/Card.js#L1 for justification.
I.e. in self-service our <Card/> extends roo-ui's <Card /> which extends <Box />, which support flex, and flexBasis, but not flexDirection or flexWrap ¯\_(ツ)_/¯ (or overflow - we're using that in one place in self-service.
=> chore: add flexDirection, flexWrap and overflow support to Box

src/components/Checkbox/Checkbox.js, src/components/Checkbox/Checkbox.test.js, src/components/Radio/Radio.js, src/components/Radio/Radio.test.js, src/components/Select/Select.js, src/components/Select/Select.test.js
Styled Components, et al, used to have an `innerRef` prop before React had proper ref forwarding support. At some point we switched to use `ref` but for got to forward it in our compound components. This PR will fix that for `Checkbox`, `Radio` and `Select`
💁‍
=> fix: ensure refs are forwarded on form components

src/components/Checkbox/Checkbox.js, src/components/Checkbox/__snapshots__/Checkbox.test.js.snap
This PR fixes a hover issue with the checkbox component by matching the input height/width with it's wrapper.
💁‍
References card: CH26138
💪
🤨
---
=> 🚧 Fix - Checkbox hover state

src/components/index.d.ts, src/logos/index.d.ts
Fix up a few issues with types I found when adopting them in Extranet UI.
---
=> fix(types): issues with type definitions

src/components/Container/Container.js
Removes styled system and `gutter` props from underlying node in `<Container />` 💁‍
---
=> fix: omit props from <Container />

src/components/index.d.ts
Export popover control render props as an interface so it can be used in consumer codebases.
---
=> fix(types): export popover control render props

src/components/index.d.ts
Add type definitions for `omitProps` in `roo-ui/components`
=> feat: add type definitions for omitProps

src/components/index.d.ts
Update `rating` on `StartRatingProps` to be `string | number`
=> fix(types): accept string or number for rating in StarRating

src/components/index.d.ts
Restricting `ref` type on interface `BaseProps` to be `React.Ref<any>` inline with emotion types
💁‍
---
=> restrict ref to React.Ref<any> to be inline with emotion

src/components/OutlineButton/OutlineButton.js, src/components/OutlineButton/__snapshots__/OutlineButton.test.js.snap
`<OutlineButton />` was rendering a hover state even if it was disabled. It was an oversight from inheriting the styling of `<Button />`.
💁‍
🤨
---
=> fix: do not display highlight state if outline button is disabled

src/components/Alert/Alert.js
Pass box props through in Alert component
💁‍
💪
🤨
---
=> refactor(alert): pass box props through

src/components/Alert/__snapshots__/Alert.test.js.snap, src/components/Checkbox/__snapshots__/Checkbox.test.js.snap, src/components/DatePicker/components/CalendarNav/__snapshots__/CalendarNav.test.js.snap, src/components/Icon/Icon.js, src/components/Icon/__snapshots__/Icon.test.js.snap, src/components/PasswordInput/__snapshots__/PasswordInput.test.js.snap
This PR allows icons to use responsive sizes by delegating width and height back to Styled System so that the following is possible:
```js
<Icon name="close" size={[16,24]} />
```
=> fix: allow icons to use responsive sizes

src/components/Alert/__snapshots__/Alert.test.js.snap, src/components/Checkbox/__snapshots__/Checkbox.test.js.snap, src/components/DatePicker/components/CalendarNav/__snapshots__/CalendarNav.test.js.snap, src/components/Icon/Icon.js, src/components/Icon/__snapshots__/Icon.test.js.snap, src/components/PasswordInput/__snapshots__/PasswordInput.test.js.snap
By adding `<title>` to the SVG tags we can make the icons more accessible, this is particularly important when creating buttons with icons, but no text.
=> fix: better a11y for svg icons

src/components/Alert/__snapshots__/Alert.test.js.snap, src/components/Checkbox/__snapshots__/Checkbox.test.js.snap, src/components/DatePicker/components/CalendarNav/__snapshots__/CalendarNav.test.js.snap, src/components/Icon/Icon.js, src/components/Icon/__snapshots__/Icon.test.js.snap, src/components/PasswordInput/__snapshots__/PasswordInput.test.js.snap
The last PR for a11y was a little off. I think we should be adding a title element if it is explicitly passed to the component, but we should not be using the `name` of the icon as a default.
Icons that are purely decoration should not have a title element, and the default behavior was adding titles to decoration icons.
=> fix: changes to titles in icons for better a11y

src/components/Label/Label.js
This PR makes the Label component more flexible so that properties like `display` and `width` can be overridden.
=> fix: make Label component more dynamic

src/components/Label/Label.js
fixing a typo that created invalid css
=> fix: typo in Label was breaking css tests

src/components/Alert/__snapshots__/Alert.test.js.snap, src/components/Checkbox/__snapshots__/Checkbox.test.js.snap, src/components/DatePicker/components/CalendarNav/__snapshots__/CalendarNav.test.js.snap, src/components/Icon/Icon.js, src/components/Icon/__snapshots__/Icon.test.js.snap, src/components/PasswordInput/__snapshots__/PasswordInput.test.js.snap
Using responsive icons causes a warning in browsers, because the size array is converted to a string and added to the SVG as an attribute. We don't need the attributes since the size is already controlled by CSS
=> fix: prevent warnings on responsive icons

src/components/index.d.ts
These props were added to Box previously but type defs weren't updated.
---
=> add missing types to box

package.json, src/components/index.d.ts, yarn.lock
Add `display` to `ContainerPropTypes`.
Also downgraded `@types/styled system` types to `^4.1.0` to match the used `styled-system` version
=> fix: add missing display prop types to Container prop types

src/components/ButtonGroup/ButtonGroup.js, src/components/ButtonGroup/ButtonGroup.story.js, src/components/ButtonGroup/ButtonGroup.test.js, src/components/ButtonGroup/ButtonGroupOption/ButtonGroupOption.js, src/components/ButtonGroup/ButtonGroupOption/ButtonGroupOption.test.js, src/components/ButtonGroup/ButtonGroupOption/__snapshots__/ButtonGroupOption.test.js.snap, src/components/ButtonGroup/ButtonGroupOption/index.js, src/components/ButtonGroup/ButtonGroupOption/primitives.js, src/components/ButtonGroup/README.md, src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap, src/components/ButtonGroup/index.js, src/components/index.d.ts, src/components/index.js, src/icons/index.d.ts
Introduces a "ButtonGroup" component, borrowed/stolen from qantas-hotels-ui.
Styles modified slightly to better support more than two options.
TODO: I need help with border width for the "selected" option and avoiding overlap (been a while since I've been back in front-end land)
💁‍
To be used in https://app.clubhouse.io/qantasaccommodation/story/48915/booking-filter-tabs .
Can also replace "ButtonGroup" in qantas-hotels-ui
💪
🤨
---
- Example: `fix(dependencies): minor version …
=> feat: add ButtonGroup component to roo-ui

src/components/ButtonGroup/README.md, src/components/index.d.ts
Corrects the typedef for ButtonGroup props. Specifically `onChange` and `size`
https://github.com/hooroo/roo-ui/pull/342
---
=> fix: correct ButtonGroupProps typedef

src/index.d.ts
"textStyles" was not part of the theme definition. I noticed this recently when converting some JS to TS in self-service (we add a couple of our own styles to the theme).
Also adds the `NestedKeyValue` type in there too, to support nested pseudo class defs (`:hover` and `:hidden`) in our additions  (thanks @ehyland for the suggestion).
---
=> fix: add textStyles to ts typedef

src/components/Alert/__snapshots__/Alert.test.js.snap, src/components/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap, src/components/DatePicker/components/CalendarDays/__snapshots__/CalendarDays.test.js.snap, src/components/DatePicker/components/CalendarNav/__snapshots__/CalendarNav.test.js.snap, src/components/DatePicker/components/CalendarWeekdays/__snapshots__/CalendarWeekdays.test.js.snap, src/components/Flex/Flex.js, src/components/Modal/components/ModalFooter/__snapshots__/ModalFooter.test.js.snap, src/components/StarRating/__snapshots__/StarRating.test.js.snap
We are currently hard coding the display value to `flex` in the `Flex` component. This is what is required 95% of the time, but it limits the ability to show and hide the component across breakpoints. This change to using defaultProps rather than hard coded properties will make it possible to hide a flexbox on the lowest break point and show it on all others. As well cater to other rare, but useful, requirements.
This would not work before, but is possible after this PR.
```js
<Flex display={['none', 'flex']}>
{children}
</Flex>
```
=> fix: use defaultProps in Flex component

src/components/Button/Button.js, src/components/OutlineButton/__snapshots__/OutlineButton.test.js.snap
Adding a focus outline to the default button component. We are updating accessibility in the QH site and the box-shadow on focus is not sufficient to distinguish the button as being focused.
This focus styling is the same styling used for `<NakedButton />`
💁‍
OLD:
NEW:
🤨
---
=> fix: adding a focus outline to the generic button component

src/components/ButtonGroup/ButtonGroupOption/__snapshots__/ButtonGroupOption.test.js.snap, src/components/ButtonGroup/ButtonGroupOption/primitives.js, src/theme.js
Button group uses a dusty grey border outline to denote that the element has focus. 
This is insufficient for focus, as the grey border and white background do not have sufficient colour contrast.
Instead, we will use a bright blue colour, as supplied by Kym. This should only display the blue outline on keyboard focus and not when the element is clicked.
💁‍
🤨
---
=> fix: distinguish button group focus state from selected state

src/components/index.d.ts
=> fix: add missing input props to typescript definition

.github/CONTRIBUTING.md
Removing Long, adding Marcel and Sam to the Maintainers list.
=> docs: Updating maintainers

src/components/Modal/index.js, src/components/index.d.ts
Users of `create-react-app` will notice a linting issue when consuming the `Modal` component's `header`, `body` or `footer` properties. Specifically, `create-react-app`'s eslint rule `react/jsx-pascal-case` expects all component names to be PascalCase or SCREAMING_SNAKE_CASE.
For example, `Modal.body` does not satisfy this. `Modal` now exports `ModalHeader`, `ModalBody` and `ModalFooter` so users of this linting rule can safely consume them.
Secondly, the `isOpen` prop was missing from the `ModalProps` interface - so users of typescript would notice a compilation error when trying to use the `Modal` component
=> Update `Modal` component exports and typing

src/components/CharacterCount/__snapshots__/CharacterCount.test.js.snap, src/theme.js
Correct normal font weight to match Ciutadella font-face.
This results in almost no visual change at base font size 
**Before - After** Small text, no visual impact
<p float="left">
</p>
**Before - After** Large text, minor visual impact
<p float="left">
</p>
---
=> fix(theme): theme value for normal font weight to match font face

package.json
After node upgrade (`roo-ui@0.91.2`), `icons/index.js` was being excluded from bundle.
This PR updates the `package.files` ignore glob to be more specific  
=> fix: files ignore glob for icon source files
