- packages/components/src/BlockLink/__snapshots__/BlockLink.test.js.snap
- packages/components/src/Box/Box.js
- packages/components/src/Box/README.md
- packages/components/src/Card/Card.js
- packages/components/src/Card/README.md
- packages/components/src/Flex/Flex.js
- packages/components/src/Flex/README.md
- packages/components/src/Heading/__snapshots__/Heading.test.js.snap
- packages/components/src/Image/Image.js
- packages/components/src/Image/README.md
- packages/components/src/Image/__snapshots__/Image.test.js.snap
- packages/components/src/Input/Input.js
- packages/components/src/Input/README.md
- packages/components/src/Input/__snapshots__/Input.test.js.snap
- packages/components/src/Label/Label.js
- packages/components/src/Label/README.md
- packages/components/src/Label/__snapshots__/Label.test.js.snap
- packages/components/src/Link/Link.js
- packages/components/src/Link/README.md
- packages/components/src/Link/__snapshots__/Link.test.js.snap
- packages/components/src/Text/Text.js
- packages/components/src/Text/__snapshots__/Text.test.js.snap
- packages/components/src/Truncate/__snapshots__/Truncate.test.js.snap
- Add **inline** variant to `<Link />` which inherits font colour and uses an underline to distinguish the link
- Add **height**, **box shadow**, and **border** styled system props to `<Box />`
- Add **height** styled system props to `<Flex />`
- Add **height**, **width** and **size** styled system props to `<Image />`
- Add **inline** variant to `<Image />` which sets display to inline
- Add **error** variant to `<Input />`
- Remove **font size**, **color** and **font weight** styled system props from `<Label />`
> refactor: change styled system props

- packages/components/src/BlockLink/__snapshots__/BlockLink.test.js.snap
- packages/components/src/Link/Link.js
- packages/components/src/Link/README.md
- packages/components/src/Link/__snapshots__/Link.test.js.snap
Adds the space property to link
Changes links display propertied to display: inline-block
> feat: add space to link

- packages/components/src/BlockLink/__snapshots__/BlockLink.test.js.snap
- packages/components/src/Link/Link.js
- packages/components/src/Link/__snapshots__/Link.test.js.snap
Provide polished `hideVisually()` on `Link`
> feat: adds hideVisually to link component

- packages/components/src/ExternalLink/ExternalLink.js
- packages/components/src/ExternalLink/ExternalLink.story.js
- packages/components/src/ExternalLink/ExternalLink.test.js
- packages/components/src/ExternalLink/README.md
- packages/components/src/ExternalLink/__snapshots__/ExternalLink.test.js.snap
- packages/components/src/ExternalLink/index.js
- packages/components/src/index.js
Adds an external Link component that extends link and has the  following attributes:
`rel="noopener noreferrer" `
`target="_blank"`
> Add external link component

- packages/components/src/Paragraph/Paragraph.js
- packages/components/src/Paragraph/Paragraph.story.js
- packages/components/src/Paragraph/Paragraph.test.js
- packages/components/src/Paragraph/README.md
- packages/components/src/Paragraph/__snapshots__/Paragraph.test.js.snap
- packages/components/src/Paragraph/index.js
- packages/components/src/Text/README.md
- packages/components/src/Text/Text.js
- packages/components/src/Text/Text.story.js
- packages/components/src/index.js
This is a breaking change but I'm publishing it as `feat` as don't think we want to go to 1.0 yet
> feat: Create Paragraph and remove Text.paragraph

- packages/components/src/Icon/Icon.story.js
> fix: labels in the icon story inherit from paragraph

- packages/components/src/Alert/Alert.js
- packages/components/src/Alert/__snapshots__/Alert.test.js.snap
- packages/components/src/Container/Container.js
- packages/components/src/Container/__snapshots__/Container.test.js.snap
Adds padding left and right to container so we get that gutter on mobile.
> feat: adds padding left/right to container

- packages/components/src/Alert/Alert.js
- packages/components/src/Alert/__snapshots__/Alert.test.js.snap
> refactor: alert style changes

- packages/themes/src/qantas.js
We've found a few cases where we need bold uppercase text.
> Add caps style

- package.json
- packages/components/src/Autocomplete/Autocomplete.js
- packages/components/src/Autocomplete/README.md
- packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.js.snap
- yarn.lock
- update downshift to v2.0.0
- remove render prop
- set default `inputValue` to `undefined`
> fix: fixes autocomplete implementation

- packages/components/src/MaskedInput/MaskedInput.js
https://github.com/text-mask/text-mask/issues/530
> fix: add workaround to update masked input values

- packages/components/src/Alert/__snapshots__/Alert.test.js.snap
- packages/components/src/CharacterCount/__snapshots__/CharacterCount.test.js.snap
- packages/components/src/Heading/__snapshots__/Heading.test.js.snap
- packages/components/src/Link/Link.story.js
- packages/components/src/Link/README.md
- packages/components/src/Paragraph/__snapshots__/Paragraph.test.js.snap
- packages/components/src/Text/README.md
- packages/components/src/Text/Text.js
- packages/components/src/Text/Text.story.js
- packages/components/src/Text/__snapshots__/Text.test.js.snap
- packages/components/src/Truncate/__snapshots__/Truncate.test.js.snap
* Add `hidden` prop to visually hide text
* Add missing docs to readme and storybook
> Add prop to visually hide text

- packages/components/src/Dropdown/Dropdown.js
- packages/components/src/Dropdown/Dropdown.story.js
- packages/components/src/Dropdown/Dropdown.test.js
- packages/components/src/Dropdown/README.md
- packages/components/src/Dropdown/__snapshots__/Dropdown.test.js.snap
- packages/components/src/Dropdown/index.js
- packages/components/src/Text/README.md
**What**
* User has control over how dropdown items appear and what the elements are
* Uses same shadow(Ben wanted to keep this consistent)
* Red on hover, darker red on focus
> Add dropdown component

- packages/components/src/index.js
> Add dropdown to index

- package.json
- packages/components/package.json
- packages/icons/package.json
- packages/logos/package.json
- packages/test-utils/package.json
- packages/themes/package.json
- yarn.lock
**What**
npm script to build and watch all workspace packages
> build: Add "build:watch" script

- .dev/styled-components/index.js
- .dev/styled-components/package.json
- CONTRIBUTING.md
- README.md
- package.json
- packages/assets/package.json
- packages/components/package.json
- packages/components/src/Autocomplete/__snapshots__/Autocomplete.test.js.snap
- packages/components/src/Checkbox/__snapshots__/Checkbox.test.js.snap
- packages/components/src/List/__snapshots__/List.test.js.snap
- packages/fonts/package.json
- packages/icons/package.json
- packages/logos/package.json
- packages/test-utils/package.json
- packages/themes/package.json
- tasks/link-app.sh
- tasks/unlink-app.sh
- yarn.lock
> Support linking roo-ui to a local app

- packages/components/src/Flex/Flex.js
- packages/components/src/Flex/README.md
> feat: add align content prop to flex

- packages/components/src/Calendar/Calendar.js
- packages/components/src/Calendar/Calendar.story.js
- packages/components/src/Calendar/Calendar.test.js
- packages/components/src/Calendar/README.md
- packages/components/src/Calendar/__snapshots__/Calendar.test.js.snap
- packages/components/src/Calendar/components/CalendarDays/CalendarDays.js
- packages/components/src/Calendar/components/CalendarDays/__snapshots__/CalendarDays.test.js.snap
Add ability to pass in array of dates to be disabled in the calendar.
> feat: add ability to disable dates on calendar

- packages/components/src/Checkbox/README.md
because noone should read w3schools
> using an appropriate link for DOM documentation

- packages/components/src/DatePicker/components/CalendarDay/CalendarDay.js
- packages/components/src/DatePicker/components/CalendarDay/__snapshots__/CalendarDay.test.js.snap
- packages/components/src/Popover/Popover.js
- packages/components/src/Popover/__snapshots__/Popover.test.js.snap
**What**
Update calendar day border styles.
**Fix**
- Darken border colour so its not the same as the background
- Change border thickness to be 1px(inline with Qantas)
- On hover/focus have a 2px border.
> fix: tweak calendar days border

- packages/assets/src/assets/index.js
- packages/assets/src/assets/rooRed.svg
> feat(assets): add red roo

- packages/components/src/DatePicker/components/CalendarDay/__snapshots__/CalendarDay.test.js.snap
- packages/components/src/DatePicker/components/CalendarNav/__snapshots__/CalendarNav.test.js.snap
- packages/components/src/Dropdown/__snapshots__/Dropdown.test.js.snap
- packages/components/src/NakedButton/NakedButton.js
- packages/components/src/NakedButton/README.md
- packages/components/src/NakedButton/__snapshots__/NakedButton.test.js.snap
> perf(NakedButton): add color prop

- packages/components/src/Truncate/Truncate.js
- packages/components/src/Truncate/__snapshots__/Truncate.test.js.snap
Fixes https://github.com/hooroo/roo-ui/issues/197
> fix: truncate component properly truncates

- packages/components/src/Select/Select.js
@talbet anything in the RooUI dev flow I should know about?
> fix(cursors): Select should have a pointer by default (CH10411)

- packages/components/src/ListItem/ListItem.js
- yarn.lock
Enables spacing and borders to be overridden on list items
> add space/borders to list item

- packages/components/src/Input/Input.js
- packages/components/src/Input/Input.story.js
- packages/components/src/PasswordInput/__snapshots__/PasswordInput.test.js.snap
Creating the new rates and inventory form, there's a need to align the contents of number inputs in the form to the right.
> add ability to change alignment of content on input field

- packages/components/src/Checkbox/Checkbox.js
The last fix to this component was in the wrong spot, this puts it in the correct spot.
> fix: fix alignment on Checkbox component

- packages/components/src/DatePicker/components/CalendarDay/__snapshots__/CalendarDay.test.js.snap
- packages/components/src/DatePicker/components/CalendarNav/__snapshots__/CalendarNav.test.js.snap
- packages/components/src/NakedButton/NakedButton.js
- packages/components/src/NakedButton/NakedButton.story.js
- packages/components/src/PasswordInput/__snapshots__/PasswordInput.test.js.snap
We have been using an intermediate component in our codebase that adds these functions to NakedButton, this backports these features and makes the component more flexible.
I have added stories to show some of the new use cases.
> fix: add StyledSystem functions to NakedButton

- packages/components/src/Container/Container.js
Just trying to clean up <Box> components in our app, this will help where we are using <Container> instead
> fix: add extra function to Container

- README.md
- src/components/List/README.md
- src/components/ListItem/ListItem.story.js
- src/components/ListItem/README.md
Menial documentation update.
Closes https://github.com/hooroo/roo-ui/issues/258
> chore: update README and remove refs to Styled Components

- src/components/Wrapper/README.md
- src/components/Wrapper/Wrapper.js
- src/components/Wrapper/Wrapper.story.js
- src/components/Wrapper/Wrapper.test.js
- src/components/Wrapper/__snapshots__/Wrapper.test.js.snap
- src/components/Wrapper/index.js
- src/components/index.js
I've added a Wrapper component that I believe could be useful. Documentation is provided for use cases in the README
> fix: add Wrapper component

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Minor update to the README
- Add PULL_REQUEST_TEMPLATE with a base check-list, including description of squash & merge message
Closes;
- https://github.com/hooroo/roo-ui/issues/267
- https://github.com/hooroo/roo-ui/issues/268
💪
---
- Example: `fix(dependencies): minor verison bump to resolve security vulnerability in set-value`
> chore(docs): add PR template. update links to the contributing doco

- .github/PULL_REQUEST_TEMPLATE.md
- _templates/entrypoint/new/package.json.t
- package.json
- src/index.d.ts
Includes `d.ts` files in bundle.
References `types` in package.json per sub-package, via the package.json.t template.
💁‍
Closes https://github.com/hooroo/roo-ui/issues/251
💪
---
> fix: add types to package.json template

- .buildkite/docker-compose.yml
- Dockerfile
Need to move to this since there was an issue with using the image which had our AWS account ID in the path. Will need to scrub the repo history once this is merged.
---
> chore: use docker hub node image

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Wee addition to the `CONTRIBUTING` (and PR template) docs.
💁‍
Closes https://github.com/hooroo/roo-ui/issues/287
💪
---
> docs: update advice on contributing to roo-ui

- package.json
- src/index.js
> feat(test utils): remove test utils export and enzyme peer dependency

- src/components/Box/Box.js
- src/components/Box/README.md
- src/components/Popover/__snapshots__/Popover.test.js.snap
adds `fontWeight` `fontSize` to box props
> feat: adds fontWeight fontSize to Box props

- src/assets/index.d.ts
- src/assets/index.js
- src/assets/tick.svg
> feat(icons): add tick icon

- src/components/Box/Box.js
- src/components/ButtonGroup/ButtonGroupOption/__snapshots__/ButtonGroupOption.test.js.snap
- src/components/Popover/__snapshots__/Popover.test.js.snap
- src/components/index.d.ts
Add `align-self` support to `<Box />` 
https://developer.mozilla.org/en-US/docs/Web/CSS/align-self
> feat: add align-self to <Box />

- src/components/Link/Link.js
- src/components/index.d.ts
> feat(link): add font size to Link

- src/components/Modal/index.js
- src/components/index.js
Fixes broken syntax which was merged in the previous PR #378
> fix(linting): Update export syntax

- package.json
Icons were missing in the last build as the babel process finished before the icons were generated. 
This PR runs the icon build script before running babel
> fix(icons): build script for icons

- .buildkite/pipeline.yml
- Dockerfile
- README.md
- package.json
- scripts/deploy-storybook
- yarn.lock
Update roo-ui to deploy to Github Pages (https://hooroo.github.io/roo-ui)
* I switched the base image as `build-storybook` requires some OS dependencies related to puppeteer aren't available in the base node version.  
💁‍
🤨
---
> feat: deploy to github pages
